### ISSUE TITLE
[Roadmap] Public Beta

### ISSUE THREAD

**Issue by madskronborg** [madskronborg/saas-toolkit#1]
### Core

- [x] SDK builder based on Httpx
- [x] Settings configuration
- [ ] Service builder
- [ ] Dynamic (Metaprogramming)

### Integrations

- [x] Redis for caching
- [ ] OpenTelemetry for observation including Request ID for distributed tracing.
- [ ] [Faststream](https://github.com/ag2ai/faststream) for async messaging.
- [ ] [Prefect](https://www.prefect.io/) for background workflows and schedules.
- [ ] Structured logging
- [ ] Remote file management (S3)

### DB

- [ ] SQLModel as ORM
- [ ] Data seeding (with faker support for generating data)
- [ ] Automatic setup of alembic

### CLI (with Typer)

- Scaffolding project
- Add domain|model|service commands
- Generating typescript client(s) from OpenAPI spec (with watch support)
- Migrations (with support for locking in distributed environments)

### Apps

- [ ] IAM (identity user, identity company, access management through workspaces. rate limiting)
- [ ] Subscriptions + marketplace (with Stripe)
- [ ] Notifications (email, REST and websockets)

### Testing

- [ ] Ensure 100% test coverage

### Documentation
- Why use kitman?
- Getting started (Scaffolding, project structure, mental model, settings, connect to DB, public / admin endpoints)
- Using the CLI for adding domains, models and services
